be/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

from . import views
app_name = 'be'

urlpatterns = [
    path('', views.home, name='home'),
    path('results/', views.results, name='results'),
]

fe/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

from . import views
app_name = 'fe'

urlpatterns = [
    path('', views.home, name='home'),
    path('results/', views.results, name='results'),
    path('faq/', views.faq, name='faq'),
    path('indeksi/', views.indeksi, name='indeksi'),
]

medex/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('medex/', permanent=True)),
    path('admin/', admin.site.urls),
    path('medex/', include('fe.urls')),
]

be/models.py
from django.db import models

# Create your models here.

fe/models.py
from django.db import models

# Create your models here.

be/views.py
#import medex.be.sources as src
from .sources.bsbi import BSBIIndex
from .sources.compression import VBEPostings

# Create your views here.

def search(query):
    return bm25(query)

def bm25(query):
    results = []
    iterat = 1
    BSBI_instance = BSBIIndex(data_dir='collection',
                              postings_encoding=VBEPostings,
                              output_dir='index')
    for (score, doc) in BSBI_instance.retrieve_bm25(query, k = 10):
        aresult = [iterat, doc, score]
        return aresult
        #if (score > .3):
            #docs_to_letor.append(doc)

fe/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.paginator import Paginator
# import medex
# import be.views as backend
# import medex.search as search
import time
import bsbi as bsbi
import compression as compression


# from be.views import *
# Create your views here.

def home(request):
    BSBI_instance = bsbi.BSBIIndex(data_dir='collection',
                                   postings_encoding=compression.VBEPostings,
                                   output_dir='index')
    ab = BSBI_instance.get_doctext_only()
    doc = ab[0]
    isi = ab[1]
    context = {"doc": doc,
               "isi": isi}
    return render(request, 'fe/home.html', context)


def faq(request):
    return render(request, 'fe/faq.html')


def indeksi(request):
    BSBI_instance = bsbi.BSBIIndex(data_dir='collection',
                                   postings_encoding=compression.VBEPostings,
                                   output_dir='index')
    BSBI_instance.index()
    len = BSBI_instance.get_len_only()
    context = {"len": len,
               "query": "A"}
    return render(request, 'fe/indeksi.html', context)


def results(request):
    result_pages = []

    query = ""
    # result_pages = [[1,"A"], [2,"B"]]
    if request.method == "POST":
        query = request.POST.get('search')
        iterat = 1
        BSBI_instance = bsbi.BSBIIndex(data_dir='collection',
                                       postings_encoding=compression.VBEPostings,
                                       output_dir='index')
        # BSBI_instance.index()
        for (score_text, doc) in BSBI_instance.retrieve_bm25(query, k=1000):
            score = score_text[0]
            teks = score_text[1]
            aresult = [iterat, doc, teks, score]
            result_pages.append(aresult)
            iterat += 1
            # return aresult
            # if (score > .3):
            # docs_to_letor.append(doc)
        for i in range(0):
            aresult = [iterat, "doc" + str(iterat), iterat, 0]
            result_pages.append(aresult)
            iterat += 1

    # paginator = Paginator(result_pages, per_page=-(result_pages//-8))
    context = {"query": query,
               "result_pages": result_pages, }
    # "pages":pages}
    return render(request, 'fe/results.html', context)

fe/templates/fe/faq.html
{% extends "base.html" %}

{% block meta %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/searches.css' %}">
{% endblock meta %}

{% block content %}


    <div class="logo">
      <img alt="medex" src="{% static 'medex_logo-removebg-preview.png' %}" height=256>
    </div>

<div class="d-flex flex-column mx-5 mt-3" style="width:65%; max-width: 700px;">
    <a href="{% url 'fe:indeksi' %}"> <img class="searx" src="{% static 'index.png' %}"
                                           title="Search"></a>
        <p>Pencett biar indeks jalan</p>

<h1>FAQ</h1>

    <h5>Yusuf Fakhri Aldrian - Information Retrieval - medex</h5>

    <h2> Memakai <a href="https://en.wikipedia.org/wiki/Okapi_BM25" target="_blank"> BM25 </a></h2>


    <h2> Sumber untuk search, indexing dll dilihat dari beberapa laman di internet</h2>
<ul>
    <li>https://github.com/har07/PySastrawi</li>

    <li>https://blog.csdn.net/jianglingbixin/article/details/109552318</li>

    <li>https://github.com/Lichuanro/Information-Retrieval-and-Web-Search</li>
</ul>

<h2> Untuk django, front-end dapat referensi</h2>
<ul>
    <li>https://github.com/SandyUndefined/Django-Search-Engine</li>

    <li>https://gitlab.com/tk-rpl-a6/ecwa-v2 (proyek RPL kelompok penulis)</li>

    <li>https://www.brandcrowd.com/maker/logo/search-love-grid-5935?text=Medex&isVariation=True (logo)</li>

    <li>Stack overflow </li>

    <li> Others: https://datatables.net/ (tidak jadi) </li>

    <li>https://info.icei.ac.id/upload/60ff9464c7a1a1.png (logo FAQ) </li>

    <li>https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Index_%28internet_news_portal%29_logo.svg/2560px-Index_%28internet_news_portal%29_logo.svg.png (logo index) </li>

    <li>https://stackoverflow.com/questions/24524318/server-clock-with-django-javascript (jam)</li>
</ul>






</div>

<br><br>

{% endblock content %}

fe/templates/fe/home.html
{% extends "base.html" %}

{% block meta %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/searches.css' %}">
{% endblock meta %}

{% block content %}
<center>

    <div class="logo">
      <img alt="medex" src="{% static 'medex_logo-removebg-preview.png' %}" height=256>
    </div>
    <div class="bar">
        <form action="{% url 'fe:results' %}" method="POST">
            {% csrf_token %}
      <input class="searchbar" type="text" placeholder="Cari" title="Search" name="search">
      <a> <input type="image" class="searx" name="submit" src="{% static 'medex_logo-removebg-preview.png' %}" title="Search"></a>
            </a>
            </form>
    </div>
    <a href="{% url 'fe:indeksi' %}"> <img class="searx" src="{% static 'index.png' %}"
                                           title="Indeks"></a>
    <br><br>
    <div class="d-flex flex-column mx-5 mt-3" style="width:65%; max-width: 700px;">
    <div class="border shadow mt-3 p-1 rounded bg-light" style="min-height:3rem;">
                        <a class="text-dark mb-1 border-bottom"><strong>Fun Fact!</strong></a>
                        <p align="left" class="text-dark mb-1 border-bottom">{{isi}}</p>
                        <a class="text-dark mb-1 border-bottom"><b>Doc:</b> {{doc}}</a>
    </div>
<!--        <div id="clock"></div>-->
    </div>
<br><br><br>
    </body></center>

{% endblock content %}

{% block script %}
<script>

function getServerTime() {
  return $.ajax({async: false}).getResponseHeader( 'Date' );
}

</script>
{% endblock script %}

fe/templates/fe/indeksi.html
{% extends "base.html" %}

{% block meta %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/searches.css' %}">
{% endblock meta %}

{% block content %}
<center>

    <div class="logo">
      <img alt="medex" src="{% static 'medex_logo-removebg-preview.png' %}" height=256>
    </div>
    <p>Panjang semuanya ada {{len}} nih.</p>
    <p>Congrats udah ngindeks BSBInya.</p>
    </body></center>


{% endblock content %}

fe/templates/fe/results.html
{% extends "base.html" %}

{% block meta %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/searches.css' %}">
<script src="{% static 'js/pagination.js' %}"></script>
{% endblock meta %}

{% block content %}
<center>

    <div class="logo-small">
        <a href="{% url 'fe:home' %}"><img alt="medex" src="{% static 'medex_logo-removebg-preview.png' %}"
                                           height=80></a>
    </div>
    <div class="bar-small">
        <form action="{% url 'fe:results' %}" method="POST">
            {% csrf_token %}
            <input class="searchbar-small" type="text" value="{{query}}" placeholder="Cari" title="Search"
                   name="search">
            <a href="{% url 'fe:indeksi' %}"> <input type="image" class="searx" name="submit" src="{% static 'medex_logo-removebg-preview.png' %}"
                       title="Search"></a>

        </form>
    </div>

    <a href="{% url 'fe:indeksi' %}"> <img class="searx" src="{% static 'index.png' %}"
                                           title="Indeks"></a>


    <center>
        <div class="d-flex flex-column mx-5 mt-3" style="width:65%; max-width: 700px;">

            <nav class="pagination-container" aria-label="Halaman pencarian">
                    <ul class="pagination">
                        <div class="page-item" id="pagination-numbers"></div>
                    </ul>
            </nav>



                {% for rp in result_pages %}

                    <div class="border shadow mt-3 p-1 rounded bg-light" style="min-height:3rem;">
                        <a class="text-dark mb-1 border-bottom"><strong>#{{rp.0}}</strong></a>
                        <p class="text-dark mb-1 border-bottom"><b>Doc:</b> {{rp.1}}</p>
                        <p align="left" class="text-dark mb-1 border-bottom"><b>Text:</b> {{rp.2}}</p>
                        <p class="text-dark mb-1 border-bottom"><b>Text:</b> {{rp.3}}</p>
                    </div>
                </tr>
                {% endfor %}




        </div>


    </center>

</center>
<br><br><br><br>

{% endblock content %}

{% block script %}
<script src="{% static 'js/pagination.js' %}"></script>
{% endblock script %}

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700&family=Poppins:wght@400;600&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/searches.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>

    <style>
        .home-height {
            min-height: calc(100vh - 56px);
        }
    </style>
    {% block meta %}
    {% endblock %}
</head>

<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand font-weight-bold" href="/">
            <img src="{% static 'medex_logo-removebg-preview.png' %}" alt="" width="32" height="32">
        </a>
        <a class="navbar-brand" href="/">Medex</a>

<!--        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"-->
<!--                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">-->
<!--            <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->

<!--        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">-->

<!--                <a class="nav-link" href="{% url 'fe:faq' %}">FAQ</a>-->
<!--                <a class="nav-link" href="#">Login</a>-->

<!--        </div>-->
    </div>
</nav>
<a href="{% url 'fe:faq' %}"> <img class="basetop" src="{% static 'faq.png' %}"
                                           title="FAQ"></a>
<br>
<a href="{% url 'fe:indeksi' %}"> <img class="basetop" src="{% static 'index.png' %}"
                                           title="Indeks"></a>

<div class="home-height">
    {% block content %}
    {% endblock content %}
</div>
</body>


<footer class="footer bg-dark text-light text-center py-3">
    &#169 Yusuf Fakhri Aldrian - Information Retrieval Fasilkom UI - medex
</footer>



    <!--
    Optional
    JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<src>
    {% block script %}
{% endblock %}
</src>


</html>